# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: 
      - '**' 
  pull_request:
    branches: [ "master", "develop" ] # production, staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x]
        os: [ubuntu-latest] # or windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodes.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Cache build output (.next)
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test --if-present

  sonarQube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: SonarQube Scan 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: npm run sonar 

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: DEBUG variable exists yet 
        env:
          EC2_USER: ${{secrets.EC2_USER}}
          EC2_HOST: ${{secrets.EC2_HOST}}
          EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}}
          TOKEN: ${{secrets.TOKEN}}

        run: | 
            echo "View variable secrets"
                if [ -z "${EC2_USER}" ] || [ -z "${EC2_HOST}" ] || [ -z "${EC2_SSH_KEY}" ] || [ -z "${TOKEN}" ]; then
                  echo "❌ One or more secrets was missing"
                  exit 1
            fi
            echo "✅ EC2_SSH_KEY was set"
            echo "✅ EC2_HOST was set"
            echo "✅ EC2_USER was set"
            echo "✅ TOKEN was set"
            echo "✅ All secrets was set"
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}


  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: staging
      url: ${{vars.URL}}     #util
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check STAGING host variable
      run: | 
            echo "View variable STAGING host"
              if [ -z "${{vars.DB_HOST_STAGING}}" ]; then
                  echo "❌ DB_HOST_STAGING is empty"
              else
                echo "✅ DB_HOST_STAGING is set: ${{vars.DB_HOST_STAGING}}"
              fi
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }} 


    - name: Deploy to EC2 via SSH in Staging
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST  }}
        username: ${{ secrets.EC2_USER  }}
        key: ${{ secrets.EC2_SSH_KEY  }}
        envs: APP_NAME
        script: |
          echo "[INFO] Start Deploy"
          bash ./scripts/deploy-staging.sh
      env:
          APP_NAME: auth

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: staging
      url: ${{vars.URL}}   #util
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check STAGING TOKEN variable
      run: | 
            echo "View variable TOKEN"
              if [ -z "${{secrets.TOKEN}}" ]; then
                  echo "❌ TOKEN is empty"
              else
                echo "✅ TOKEN is set: ${{secrets.TOKEN}}"
              fi
            echo "View variable github.actor"
              if [ -z "${{github.actor}}" ]; then
                  echo "❌ Dgithub.actor is empty"
              else
                echo "✅ github.actor is set: ${{github.actor}}"
              fi
    # - name: Log in to GHCR
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.TOKEN }} 

    - name: Deploy to EC2 via SSH in Production
      if: github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu 
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: APP_NAME
        script: |
          echo "---------- Start deploy-prod.sh on EC2 ----------"
          chmod +x /home/ubuntu/scripts/deploy-prod.sh
          bash /home/ubuntu/scripts/deploy-prod.sh
          echo "---------- Finished deploy-prod.sh ----------"
      env:
        APP_NAME: auth

    # - name: Notify
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TG_CHAT_ID }}
    #     token: ${{ secrets.TG_BOT_TOKEN }}
    #     message: "🚨 Deploy failed at ${{ github.sha }}"
          

